trouve_blog_homepage:
    pattern:  /
    defaults: { _controller: TrouveBlogBundle:Index:index }
trouve_blog_newPost:
    pattern:  /post/new
    defaults: { _controller: TrouveBlogBundle:Post:new }
trouve_blog_postShow:
    path:   /{slug}
    defaults:  { _controller: TrouveBlogBundle:Post:show }