parameters:
#    trouve_blog.example.class: Trouve\BlogBundle\Example

services:
#    trouve_blog.example:
#        class: %trouve_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
