generator: admingenerator.generator.doctrine
params:
    model: Trouve\BlogBundle\Entity\Comment
    namespace_prefix: Trouve
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
    i18n_catalog: comment
builders:
    list:
        params:
            title: List comments
            display: [body,post,created,updated]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New comment
            display: [post, body]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Edition comment "
            display: [post, body]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object "
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
